version: "3.9"

x-common-variables: &common-variables
  MYSQL_USER: usertesting
  MYSQL_PASSWORD: passwordtesting
  MYSQL_DATABASE: online_classes
  REACT_APP_SERVER_PORT: 8000

services:
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./database:/var/lib/mysql:rw
    networks:
      - chatnetwork
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    restart: always
    networks:
      - chatnetwork
  server:
    build:
      context: ./docker-files/backend/
      dockerfile: Dockerfile
    depends_on:
      - mysql
    expose:
      - 8000
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
    ports:
      - 8000:8000
    volumes:
      - './projects/backend:/app'
    command: yarn start
    networks:
      - chatnetwork
  client:
    build:
      context: ./docker-files/frontend/
      dockerfile: Dockerfile
    environment:
      <<: *common-variables
      NODE_PATH: src
    env_file:
      - './projects/frontend/.env'
    expose:
      - 3000
    ports:
      - 3001:3000
    volumes:
      - './projects/frontend:/app'
    links:
      - server
    command: yarn start
    networks:
      - chatnetwork
networks:
  chatnetwork: